USE DATABASE DEV_DB;

CREATE SCHEMA IF NOT EXISTS DEV_DB.BRONZE_SC;
CREATE SCHEMA IF NOT EXISTS DEV_DB.SILVER_SC;



create or replace TABLE BRONZE_SC.EMP (
	ID VARCHAR(200),
	FIRST_NAME VARCHAR(200),
	LAST_NAME VARCHAR(200),
	EMAIL VARCHAR(200),
	LOCATION VARCHAR(200),
	DEPARTMENT VARCHAR(200)
);

create or replace TABLE SILVER_SCEMP_T(
	ID VARCHAR(200),
	FIRST_NAME VARCHAR(200),
	LAST_NAME VARCHAR(200),
	EMAIL VARCHAR(200),
	LOCATION VARCHAR(200),
	DEPARTMENT VARCHAR(200),
    PRIMARY KEY(ID)
);
